version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'Passw0rd!'
    ports:
      - '1433:1433'
    volumes:
      - mssql_data:/var/opt/mssql

  aspnetapp:
    build: 
      context: ./JetstreamApi
      dockerfile: Dockerfile 
    volumes:
      - migration_volume:/tmp
      - ./Logs:/Logs
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__ServiceRequestDbConnectionString=Server=mssql,1433;Database=JetStreamServiceRequest;User ID=SA;Password=Passw0rd!;TrustServerCertificate=True;
    ports:
      - "8000:80"
    depends_on:
      - mssql

  migrate:
    build:
      context: ./JetstreamApi
      dockerfile: Dockerfile.Migrate
    volumes:
      - migration_volume:/tmp
    depends_on:
      - mssql

volumes:
  mssql_data: {}
  migration_volume: {}
